/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { TelagentGroupRegistry__factory } from "./TelagentGroupRegistry__factory";
