/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockClawIdentity__factory } from "./MockClawIdentity__factory";
export { MockClawRouter__factory } from "./MockClawRouter__factory";
