/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockClawIdentity,
  MockClawIdentityInterface,
} from "../../../contracts/mocks/MockClawIdentity";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "active",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "controller",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
    ],
    name: "getController",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
    ],
    name: "isActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "didController",
        type: "address",
      },
      {
        internalType: "bool",
        name: "activeFlag",
        type: "bool",
      },
    ],
    name: "setDid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102198061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80635c36901c1461005c5780638f1815b214610094578063dbd4e021146100d5578063e26e4cf9146100fe578063ef326f4914610121575b600080fd5b61007f61006a366004610177565b60009081526020819052604090205460ff1690565b60405190151581526020015b60405180910390f35b6100bd6100a2366004610177565b6000908152600160205260409020546001600160a01b031690565b6040516001600160a01b03909116815260200161008b565b6100bd6100e3366004610177565b6001602052600090815260409020546001600160a01b031681565b61007f61010c366004610177565b60006020819052908152604090205460ff1681565b61017561012f366004610190565b600092835260016020908152604080852080546001600160a01b0319166001600160a01b0395909516949094179093558390529120805460ff1916911515919091179055565b005b60006020828403121561018957600080fd5b5035919050565b6000806000606084860312156101a557600080fd5b8335925060208401356001600160a01b03811681146101c357600080fd5b9150604084013580151581146101d857600080fd5b80915050925092509256fea26469706673582212202cf692a42c0937f810db33ed745eff3ae2cc6562addef91e83e3321dc87b185364736f6c634300081c0033";

type MockClawIdentityConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockClawIdentityConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockClawIdentity__factory extends ContractFactory {
  constructor(...args: MockClawIdentityConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockClawIdentity & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockClawIdentity__factory {
    return super.connect(runner) as MockClawIdentity__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockClawIdentityInterface {
    return new Interface(_abi) as MockClawIdentityInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockClawIdentity {
    return new Contract(address, _abi, runner) as unknown as MockClawIdentity;
  }
}
