#!/usr/bin/env node

import { balanceOf, logStep, nowIso, sleep, toInt } from './bot-lib.mjs';

function account(rt, name) {
  const value = rt.config.accounts?.[name];
  if (!value) {
    throw new Error(`Account not configured: ${name}`);
  }
  return value;
}

async function getWallet(rt, didOrAddress) {
  return rt.api('GET', `/api/v1/wallets/${encodeURIComponent(didOrAddress)}`);
}

async function transfer(rt, fromName, toDidOrAddress, amount, memo) {
  if (amount <= 0) return null;
  const from = account(rt, fromName);
  return rt.api('POST', '/api/v1/transfers', {
    did: from.did,
    passphrase: from.passphrase,
    nonce: rt.nextNonceFor(from.did),
    to: toDidOrAddress,
    amount,
    memo,
  });
}

function addRun(rt, entry) {
  rt.state.runs.push({
    ...entry,
    at: nowIso(),
  });
}

export async function healthCheck(rt) {
  logStep('Health Check');
  const node = await rt.api('GET', '/api/v1/node');
  const summary = {
    checkedAt: nowIso(),
    node: {
      did: node?.did ?? null,
      peerCount: node?.peerCount ?? null,
      uptime: node?.uptime ?? null,
      chainId: node?.config?.chain?.chainId ?? null,
    },
    balances: {},
  };

  for (const name of ['liquidityVault', 'maker', 'taker']) {
    const acc = account(rt, name);
    const wallet = await getWallet(rt, acc.did);
    summary.balances[name] = {
      did: acc.did,
      balance: balanceOf(wallet),
      available: toInt(wallet?.available, 0),
      locked: toInt(wallet?.locked, 0),
    };
  }

  rt.state.lastHealth = summary;
  addRun(rt, { type: 'health_check', summary });
  await rt.save();
  // eslint-disable-next-line no-console
  console.log(JSON.stringify(summary, null, 2));
  return summary;
}

export async function fundOperators(rt) {
  logStep('Fund Operators');
  const maker = account(rt, 'maker');
  const taker = account(rt, 'taker');
  const vault = account(rt, 'liquidityVault');

  const vaultWallet = await getWallet(rt, vault.did);
  const makerWallet = await getWallet(rt, maker.did);
  const takerWallet = await getWallet(rt, taker.did);

  const vaultBalance = balanceOf(vaultWallet);
  const makerBalance = balanceOf(makerWallet);
  const takerBalance = balanceOf(takerWallet);

  const makerNeed = Math.max(0, rt.config.funding.targetMakerBalance - makerBalance);
  const takerNeed = Math.max(0, rt.config.funding.targetTakerBalance - takerBalance);
  const totalNeed = makerNeed + takerNeed;

  if (totalNeed === 0) {
    // eslint-disable-next-line no-console
    console.log('No top-up needed; operator balances already meet targets.');
    return {
      makerNeed: 0,
      takerNeed: 0,
      transfers: [],
    };
  }

  if (totalNeed > rt.config.funding.maxTransferPerRun) {
    throw new Error(
      `Top-up ${totalNeed} exceeds maxTransferPerRun ${rt.config.funding.maxTransferPerRun}`,
    );
  }
  if (totalNeed > vaultBalance) {
    throw new Error(`Liquidity vault balance ${vaultBalance} is lower than required top-up ${totalNeed}`);
  }

  const transfers = [];
  if (makerNeed > 0) {
    const result = await transfer(
      rt,
      'liquidityVault',
      maker.did,
      makerNeed,
      'liquidity-bot:topup-maker',
    );
    transfers.push({ to: maker.did, amount: makerNeed, txHash: result?.txHash ?? null });
  }
  if (takerNeed > 0) {
    const result = await transfer(
      rt,
      'liquidityVault',
      taker.did,
      takerNeed,
      'liquidity-bot:topup-taker',
    );
    transfers.push({ to: taker.did, amount: takerNeed, txHash: result?.txHash ?? null });
  }

  const summary = { makerNeed, takerNeed, transfers };
  addRun(rt, { type: 'fund_operators', summary });
  await rt.save();
  // eslint-disable-next-line no-console
  console.log(JSON.stringify(summary, null, 2));
  return summary;
}

function buildInfoListingPayload(rt, index, price) {
  const maker = account(rt, 'maker');
  const suffix = `${Date.now()}-${index + 1}`;
  return {
    did: maker.did,
    passphrase: maker.passphrase,
    nonce: rt.nextNonceFor(maker.did),
    listingId: `lq-info-${suffix}`,
    title: `Liquidity bootstrap listing #${index + 1}`,
    description: 'Synthetic listing generated by liquidity bot for testnet trading flow.',
    category: rt.config.market.category,
    tags: ['liquidity', 'bootstrap', 'testnet'],
    pricing: {
      type: 'fixed',
      fixedPrice: String(price),
      negotiable: false,
      currency: 'TOKEN',
    },
    visibility: 'public',
    infoType: rt.config.market.infoType,
    content: {
      format: 'json',
      preview: {
        type: 'summary',
        content: `Sample payload for cycle ${index + 1}`,
        truncated: false,
      },
      schema: { name: 'liquidity-bootstrap', format: 'json', version: '1.0' },
    },
    accessMethod: {
      type: 'download',
      download: {
        formats: ['json'],
        maxDownloads: 1_000,
      },
    },
    license: {
      type: 'limited',
      permissions: {
        use: true,
        modify: false,
        distribute: false,
        commercialize: false,
        sublicense: false,
      },
      restrictions: {
        attribution: true,
        shareAlike: false,
        nonCompete: false,
        confidential: false,
      },
    },
    usageRestrictions: {
      derivativeWorks: false,
      resale: false,
      allowedPurposes: ['testing'],
      prohibitedPurposes: ['production'],
    },
  };
}

export async function publishListings(rt, options = {}) {
  logStep('Publish Info Listings');
  const count = Math.max(1, toInt(options.count, rt.config.market.listingCount));
  const basePrice = Math.max(1, toInt(rt.config.market.basePrice, 10));
  const priceStep = Math.max(0, toInt(rt.config.market.priceStep, 2));

  const published = [];
  for (let i = 0; i < count; i += 1) {
    const price = basePrice + i * priceStep;
    const payload = buildInfoListingPayload(rt, i, price);
    const result = await rt.api('POST', '/api/v1/markets/info', payload);
    const listingId = result?.listingId ?? payload.listingId;
    const record = {
      listingId,
      price,
      sellerDid: account(rt, 'maker').did,
      publishedAt: nowIso(),
      status: 'active',
      txHash: result?.txHash ?? null,
    };
    rt.state.listings.push(record);
    published.push(record);
  }

  addRun(rt, { type: 'publish_listings', count, published });
  await rt.save();
  // eslint-disable-next-line no-console
  console.log(JSON.stringify({ count, published }, null, 2));
  return published;
}

function pickListings(rt) {
  return rt.state.listings.filter((item) => item && item.status !== 'removed');
}

export async function runTradeCycles(rt, options = {}) {
  logStep('Run Trade Cycles');
  const maker = account(rt, 'maker');
  const taker = account(rt, 'taker');
  const listings = pickListings(rt);
  if (listings.length === 0) {
    throw new Error('No active listings in state. Run publish-listings first.');
  }

  const cycles = Math.max(1, toInt(options.cycles, rt.config.trade.cycles));
  const quantity = Math.max(1, toInt(rt.config.trade.quantity, 1));
  const waitMs = Math.max(0, toInt(rt.config.trade.waitMs, 0));

  const executed = [];

  for (let i = 0; i < cycles; i += 1) {
    const listing = listings[i % listings.length];
    const unitPrice = Math.max(1, toInt(listing.price, 1));
    const orderId = `lq-order-${Date.now()}-${i + 1}`;

    const purchase = await rt.api(
      'POST',
      `/api/v1/markets/info/${encodeURIComponent(listing.listingId)}/actions/purchase`,
      {
        did: taker.did,
        passphrase: taker.passphrase,
        nonce: rt.nextNonceFor(taker.did),
        orderId,
        quantity,
        unitPrice: String(unitPrice),
        sellerDid: maker.did,
        releaseRules: [{ type: 'delivery_confirmation' }],
      },
    );

    await sleep(waitMs);

    const deliver = await rt.api(
      'POST',
      `/api/v1/markets/info/${encodeURIComponent(listing.listingId)}/actions/deliver`,
      {
        did: maker.did,
        passphrase: maker.passphrase,
        nonce: rt.nextNonceFor(maker.did),
        orderId: purchase.orderId ?? orderId,
        deliveryId: `lq-delivery-${Date.now()}-${i + 1}`,
        method: 'direct',
        accessUrl: `https://example.invalid/liquidity/${purchase.orderId ?? orderId}`,
      },
    );

    await sleep(waitMs);

    const confirm = await rt.api(
      'POST',
      `/api/v1/markets/info/${encodeURIComponent(listing.listingId)}/actions/confirm`,
      {
        did: taker.did,
        passphrase: taker.passphrase,
        nonce: rt.nextNonceFor(taker.did),
        orderId: purchase.orderId ?? orderId,
        escrowId: purchase.escrowId,
        amount: String(unitPrice * quantity),
        ruleId: 'delivery_confirmation',
      },
    );

    const orderRecord = {
      listingId: listing.listingId,
      orderId: purchase.orderId ?? orderId,
      escrowId: purchase.escrowId ?? null,
      quantity,
      unitPrice,
      purchaseHash: purchase.paymentHash ?? purchase.orderHash ?? null,
      deliveryHash: deliver.orderUpdateHash ?? null,
      confirmHash: confirm.orderUpdateHash ?? null,
      completedAt: nowIso(),
    };
    rt.state.orders.push(orderRecord);
    executed.push(orderRecord);
  }

  addRun(rt, { type: 'trade_cycles', cycles, executed });
  await rt.save();
  // eslint-disable-next-line no-console
  console.log(JSON.stringify({ cycles, executed }, null, 2));
  return executed;
}

export async function reconcile(rt) {
  logStep('Reconcile Operator Balances');
  const vault = account(rt, 'liquidityVault');
  const keep = Math.max(0, toInt(rt.config.funding.reconcileMinKeep, 50));
  const actions = [];

  for (const name of ['maker', 'taker']) {
    const operator = account(rt, name);
    const wallet = await getWallet(rt, operator.did);
    const balance = balanceOf(wallet);
    const refund = Math.max(0, balance - keep);
    if (refund <= 0) {
      actions.push({ operator: name, refunded: 0, reason: 'below_keep_threshold' });
      continue;
    }
    const result = await transfer(
      rt,
      name,
      vault.did,
      refund,
      `liquidity-bot:reconcile-${name}`,
    );
    actions.push({
      operator: name,
      refunded: refund,
      txHash: result?.txHash ?? null,
    });
  }

  addRun(rt, { type: 'reconcile', keep, actions });
  await rt.save();
  // eslint-disable-next-line no-console
  console.log(JSON.stringify({ keep, actions }, null, 2));
  return actions;
}
