/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IClawIdentityInterface extends Interface {
  getFunction(
    nameOrSignature: "getController" | "isActive" | "selfRegisterDID"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getController",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "selfRegisterDID",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "selfRegisterDID",
    data: BytesLike
  ): Result;
}

export interface IClawIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): IClawIdentity;
  waitForDeployment(): Promise<this>;

  interface: IClawIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getController: TypedContractMethod<[didHash: BytesLike], [string], "view">;

  isActive: TypedContractMethod<[didHash: BytesLike], [boolean], "view">;

  selfRegisterDID: TypedContractMethod<
    [didHash: BytesLike, publicKey: BytesLike, purpose: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getController"
  ): TypedContractMethod<[didHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[didHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "selfRegisterDID"
  ): TypedContractMethod<
    [didHash: BytesLike, publicKey: BytesLike, purpose: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
