/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClawIdentity,
  IClawIdentityInterface,
} from "../../../contracts/interfaces/IClawIdentity";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
    ],
    name: "getController",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
    ],
    name: "isActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "publicKey",
        type: "bytes",
      },
      {
        internalType: "uint8",
        name: "purpose",
        type: "uint8",
      },
    ],
    name: "selfRegisterDID",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IClawIdentity__factory {
  static readonly abi = _abi;
  static createInterface(): IClawIdentityInterface {
    return new Interface(_abi) as IClawIdentityInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClawIdentity {
    return new Contract(address, _abi, runner) as unknown as IClawIdentity;
  }
}
