/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockClawIdentity } from "./MockClawIdentity";
export type { MockClawRouter } from "./MockClawRouter";
