/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockClawRouterInterface extends Interface {
  getFunction(
    nameOrSignature: "getModuleOrZero" | "registerModule"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ModuleRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getModuleOrZero",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerModule",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getModuleOrZero",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerModule",
    data: BytesLike
  ): Result;
}

export namespace ModuleRegisteredEvent {
  export type InputTuple = [key: BytesLike, module: AddressLike];
  export type OutputTuple = [key: string, module: string];
  export interface OutputObject {
    key: string;
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockClawRouter extends BaseContract {
  connect(runner?: ContractRunner | null): MockClawRouter;
  waitForDeployment(): Promise<this>;

  interface: MockClawRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getModuleOrZero: TypedContractMethod<[key: BytesLike], [string], "view">;

  registerModule: TypedContractMethod<
    [key: BytesLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getModuleOrZero"
  ): TypedContractMethod<[key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerModule"
  ): TypedContractMethod<
    [key: BytesLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ModuleRegistered"
  ): TypedContractEvent<
    ModuleRegisteredEvent.InputTuple,
    ModuleRegisteredEvent.OutputTuple,
    ModuleRegisteredEvent.OutputObject
  >;

  filters: {
    "ModuleRegistered(bytes32,address)": TypedContractEvent<
      ModuleRegisteredEvent.InputTuple,
      ModuleRegisteredEvent.OutputTuple,
      ModuleRegisteredEvent.OutputObject
    >;
    ModuleRegistered: TypedContractEvent<
      ModuleRegisteredEvent.InputTuple,
      ModuleRegisteredEvent.OutputTuple,
      ModuleRegisteredEvent.OutputObject
    >;
  };
}
