/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockClawIdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "active"
      | "controller"
      | "getController"
      | "isActive"
      | "setDid"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "active", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "controller",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getController",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setDid",
    values: [BytesLike, AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "active", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDid", data: BytesLike): Result;
}

export interface MockClawIdentity extends BaseContract {
  connect(runner?: ContractRunner | null): MockClawIdentity;
  waitForDeployment(): Promise<this>;

  interface: MockClawIdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  active: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  controller: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getController: TypedContractMethod<[didHash: BytesLike], [string], "view">;

  isActive: TypedContractMethod<[didHash: BytesLike], [boolean], "view">;

  setDid: TypedContractMethod<
    [didHash: BytesLike, didController: AddressLike, activeFlag: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "active"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "controller"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getController"
  ): TypedContractMethod<[didHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[didHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setDid"
  ): TypedContractMethod<
    [didHash: BytesLike, didController: AddressLike, activeFlag: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
