/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TelagentGroupRegistry {
  export type GroupRecordStruct = {
    creatorDidHash: BytesLike;
    groupDomain: string;
    domainProofHash: BytesLike;
    mlsStateHash: BytesLike;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    active: boolean;
  };

  export type GroupRecordStructOutput = [
    creatorDidHash: string,
    groupDomain: string,
    domainProofHash: string,
    mlsStateHash: string,
    createdAt: bigint,
    updatedAt: bigint,
    active: boolean
  ] & {
    creatorDidHash: string;
    groupDomain: string;
    domainProofHash: string;
    mlsStateHash: string;
    createdAt: bigint;
    updatedAt: bigint;
    active: boolean;
  };
}

export interface TelagentGroupRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "PAUSER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptInvite"
      | "createGroup"
      | "getGroup"
      | "getMemberState"
      | "getRoleAdmin"
      | "grantRole"
      | "groups"
      | "hasRole"
      | "identity"
      | "initialize"
      | "inviteMember"
      | "invites"
      | "isFinalizedMember"
      | "members"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "removeMember"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "unpause"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GroupCreated"
      | "Initialized"
      | "MemberAccepted"
      | "MemberInvited"
      | "MemberRemoved"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptInvite",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createGroup",
    values: [BytesLike, BytesLike, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getGroup", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getMemberState",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "groups", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "identity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inviteMember",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invites",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFinalizedMember",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptInvite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGroup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "groups", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inviteMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invites", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFinalizedMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace GroupCreatedEvent {
  export type InputTuple = [
    groupId: BytesLike,
    creatorDidHash: BytesLike,
    domainHash: BytesLike,
    domainProofHash: BytesLike,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [
    groupId: string,
    creatorDidHash: string,
    domainHash: string,
    domainProofHash: string,
    blockNumber: bigint
  ];
  export interface OutputObject {
    groupId: string;
    creatorDidHash: string;
    domainHash: string;
    domainProofHash: string;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberAcceptedEvent {
  export type InputTuple = [
    groupId: BytesLike,
    inviteId: BytesLike,
    memberDidHash: BytesLike,
    mlsWelcomeHash: BytesLike
  ];
  export type OutputTuple = [
    groupId: string,
    inviteId: string,
    memberDidHash: string,
    mlsWelcomeHash: string
  ];
  export interface OutputObject {
    groupId: string;
    inviteId: string;
    memberDidHash: string;
    mlsWelcomeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberInvitedEvent {
  export type InputTuple = [
    groupId: BytesLike,
    inviteId: BytesLike,
    inviterDidHash: BytesLike,
    inviteeDidHash: BytesLike,
    mlsCommitHash: BytesLike
  ];
  export type OutputTuple = [
    groupId: string,
    inviteId: string,
    inviterDidHash: string,
    inviteeDidHash: string,
    mlsCommitHash: string
  ];
  export interface OutputObject {
    groupId: string;
    inviteId: string;
    inviterDidHash: string;
    inviteeDidHash: string;
    mlsCommitHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [
    groupId: BytesLike,
    memberDidHash: BytesLike,
    operatorDidHash: BytesLike,
    mlsCommitHash: BytesLike
  ];
  export type OutputTuple = [
    groupId: string,
    memberDidHash: string,
    operatorDidHash: string,
    mlsCommitHash: string
  ];
  export interface OutputObject {
    groupId: string;
    memberDidHash: string;
    operatorDidHash: string;
    mlsCommitHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TelagentGroupRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): TelagentGroupRegistry;
  waitForDeployment(): Promise<this>;

  interface: TelagentGroupRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptInvite: TypedContractMethod<
    [
      groupId: BytesLike,
      inviteId: BytesLike,
      inviteeDidHash: BytesLike,
      mlsWelcomeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createGroup: TypedContractMethod<
    [
      groupId: BytesLike,
      creatorDidHash: BytesLike,
      groupDomain: string,
      domainProofHash: BytesLike,
      initialMlsStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getGroup: TypedContractMethod<
    [groupId: BytesLike],
    [TelagentGroupRegistry.GroupRecordStructOutput],
    "view"
  >;

  getMemberState: TypedContractMethod<
    [groupId: BytesLike, memberDidHash: BytesLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  groups: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        creatorDidHash: string;
        groupDomain: string;
        domainProofHash: string;
        mlsStateHash: string;
        createdAt: bigint;
        updatedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  identity: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [admin: AddressLike, identityAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  inviteMember: TypedContractMethod<
    [
      groupId: BytesLike,
      inviteId: BytesLike,
      inviterDidHash: BytesLike,
      inviteeDidHash: BytesLike,
      mlsCommitHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  invites: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, string, boolean, boolean] & {
        inviterDidHash: string;
        inviteeDidHash: string;
        exists: boolean;
        accepted: boolean;
      }
    ],
    "view"
  >;

  isFinalizedMember: TypedContractMethod<
    [groupId: BytesLike, memberDidHash: BytesLike],
    [boolean],
    "view"
  >;

  members: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeMember: TypedContractMethod<
    [
      groupId: BytesLike,
      operatorDidHash: BytesLike,
      memberDidHash: BytesLike,
      mlsCommitHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptInvite"
  ): TypedContractMethod<
    [
      groupId: BytesLike,
      inviteId: BytesLike,
      inviteeDidHash: BytesLike,
      mlsWelcomeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createGroup"
  ): TypedContractMethod<
    [
      groupId: BytesLike,
      creatorDidHash: BytesLike,
      groupDomain: string,
      domainProofHash: BytesLike,
      initialMlsStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGroup"
  ): TypedContractMethod<
    [groupId: BytesLike],
    [TelagentGroupRegistry.GroupRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMemberState"
  ): TypedContractMethod<
    [groupId: BytesLike, memberDidHash: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "groups"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        creatorDidHash: string;
        groupDomain: string;
        domainProofHash: string;
        mlsStateHash: string;
        createdAt: bigint;
        updatedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [admin: AddressLike, identityAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "inviteMember"
  ): TypedContractMethod<
    [
      groupId: BytesLike,
      inviteId: BytesLike,
      inviterDidHash: BytesLike,
      inviteeDidHash: BytesLike,
      mlsCommitHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "invites"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [
      [string, string, boolean, boolean] & {
        inviterDidHash: string;
        inviteeDidHash: string;
        exists: boolean;
        accepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFinalizedMember"
  ): TypedContractMethod<
    [groupId: BytesLike, memberDidHash: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [
      groupId: BytesLike,
      operatorDidHash: BytesLike,
      memberDidHash: BytesLike,
      mlsCommitHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "GroupCreated"
  ): TypedContractEvent<
    GroupCreatedEvent.InputTuple,
    GroupCreatedEvent.OutputTuple,
    GroupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MemberAccepted"
  ): TypedContractEvent<
    MemberAcceptedEvent.InputTuple,
    MemberAcceptedEvent.OutputTuple,
    MemberAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "MemberInvited"
  ): TypedContractEvent<
    MemberInvitedEvent.InputTuple,
    MemberInvitedEvent.OutputTuple,
    MemberInvitedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "GroupCreated(bytes32,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;
    GroupCreated: TypedContractEvent<
      GroupCreatedEvent.InputTuple,
      GroupCreatedEvent.OutputTuple,
      GroupCreatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MemberAccepted(bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      MemberAcceptedEvent.InputTuple,
      MemberAcceptedEvent.OutputTuple,
      MemberAcceptedEvent.OutputObject
    >;
    MemberAccepted: TypedContractEvent<
      MemberAcceptedEvent.InputTuple,
      MemberAcceptedEvent.OutputTuple,
      MemberAcceptedEvent.OutputObject
    >;

    "MemberInvited(bytes32,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      MemberInvitedEvent.InputTuple,
      MemberInvitedEvent.OutputTuple,
      MemberInvitedEvent.OutputObject
    >;
    MemberInvited: TypedContractEvent<
      MemberInvitedEvent.InputTuple,
      MemberInvitedEvent.OutputTuple,
      MemberInvitedEvent.OutputObject
    >;

    "MemberRemoved(bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
